---
- name: Create systemd unit file for Docker Compose
  copy:
    dest: /etc/systemd/system/cloud1.service
    content: |
      [Unit]
      Description=Cloud-1 Docker Compose App
      Requires=docker.service
      After=docker.service
      StartLimitIntervalSec=60
      StartLimitBurst=3

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      WorkingDirectory=/opt/cloud1
      ExecStart=/usr/bin/docker compose up -d --build
      ExecStop=/usr/bin/docker compose down
      TimeoutStartSec=5min  

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reexec

- name: Reload systemd again to include new service
  command: systemctl daemon-reload

- name: Enable Cloud1 Docker Compose service on boot
  systemd:
    name: cloud1
    enabled: true

- name: Start Docker Compose service
  systemd:
    name: cloud1
    state: started
