services:
  wordpress:
    image: wordpress:6.4.3-php8.2-fpm
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${RDS_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wordpress-data:/var/www/html
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/wp-login.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: ${RDS_HOST}
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - ./phpmyadmin/apache-servername.conf:/etc/apache2/conf-enabled/servername.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - wordpress
    networks:
      - app

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - wordpress-data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - wordpress
      - phpmyadmin
    networks:
      - app

volumes:
  wordpress-data:

networks:
  app: