---
- name: Ensure required system packages are installed
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes
  tags: install_docker

- name: Create directory for Docker keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: install_docker

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags: install_docker

- name: Affiche les facts importants
  debug:
    msg: "arch={{ ansible_architecture }}, codename={{ ansible_lsb.codename }}"

- name: Add Docker APT repository (valid single line)
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu focal stable"
    create: yes
    mode: '0644'
  tags: install_docker



- name: Update APT cache
  apt:
    update_cache: yes
  tags: install_docker

- name: Install Docker components
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify:
    - Restart Docker
  tags: install_docker

- name: Create Docker CLI plugins directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  tags: install_docker

- name: Install Docker Compose v2 binary
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'
  tags: install_docker

- name: Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false
  tags: verify_docker

- name: Display Docker version
  debug:
    msg: "{{ docker_version.stdout }}"
  tags: verify_docker
