---
- name: Install and configure Docker and run it on EC2 via SSM
  hosts: all
  become: true
  gather_facts: true

  vars:
    ansible_connection: community.aws.aws_ssm
    ansible_aws_ssm_bucket_name: cloud1-static-assets-123456
    ansible_aws_ssm_region: eu-north-1

  vars_files:
  - terraform_outputs.yml

  roles:
  - docker
  - docker_compose
  - systemd_docker