{
  "alb_dns": "cloud1-alb-364799873.eu-north-1.elb.amazonaws.com",
  "bucket_name": "cloud1-static-assets-123456",
  "ec2_instance_id": "i-0c67b3af7b73ea285",
  "ec2_public_ip": "51.21.253.16",
  "rds_endpoint": "cloud1-db.crg2022w29n3.eu-north-1.rds.amazonaws.com"
}
